language: r
cache: packages
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: xenial
      env: EXTERNAL_QPDF=true
      addons:
        apt:
          packages: libqpdf-dev
    - os: osx
    - os: osx
      osx_image: xcode7.3

notifications:
  email:
    on_success: change
    on_failure: change
