language: r
cache: packages
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: xenial
      r: 3.4
    - os: osx
    - os: osx
      osx_image: xcode7.3

#brew_packages: jpeg

notifications:
  email:
    on_success: change
    on_failure: change
