language: r
cache: packages
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

notifications:
  email:
    on_success: change
    on_failure: change
