language: r
cache: packages
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: qpdf
      env: EXTERNAL_QPDF=true
    - os: osx
    - os: osx
      osx_image: xcode7.3

notifications:
  email:
    on_success: change
    on_failure: change
